/// Label italiane del catalogo CAF operativo (`op_*`).
/// Generato da wecoop-backend/src/data/caf-operativo-catalog.ts — non editare a mano.
library;

const Map<String, String> kOperativoServiceLabels = {
  "op_730_unico_imu__730_autocompilato_cartaceo_iscritto_assistenza": "730 AUTOCOMPILATO CARTACEO ISCRITTO assistenza",
  "op_730_unico_imu__730_autocompilato_cartaceo_non_iscritto_assistenza": "730 AUTOCOMPILATO CARTACEO NON ISCRITTO assistenza",
  "op_730_unico_imu__730_congiunta_iscritto_con_coniuge_iscritto": "730 CONGIUNTA (iscritto con coniuge iscritto)",
  "op_730_unico_imu__730_congiunta_iscritto_con_coniuge_non_iscritto": "730 CONGIUNTA (iscritto con coniuge non iscritto)",
  "op_730_unico_imu__730_congiunta_non_iscritto_con_coniuge_non_iscritto": "730 CONGIUNTA (non iscritto con coniuge non iscritto)",
  "op_730_unico_imu__730_o_mod_redditi_integrativo_di_pratica_gia_elaborata_al_co": "730 o mod.REDDITI INTEGRATIVO (di pratica già elaborata al CONCAF)",
  "op_730_unico_imu__730_o_mod_redditi_integrativo_di_pratica_gia_elaborata_in_un": "730 o mod.REDDITI INTEGRATIVO (di pratica già elaborata in un altro CAF)",
  "op_730_unico_imu__730_o_mod_redditi_ristampa_per_successive_integrazioni_docum": "730 o mod.REDDITI RISTAMPA (per successive integrazioni documenti che cambiano il risultato contabile)",
  "op_730_unico_imu__730_singola_iscritto": "730 SINGOLA ISCRITTO",
  "op_730_unico_imu__730_singola_non_iscritto": "730 SINGOLA NON ISCRITTO",
  "op_730_unico_imu__imu_dichiarazione_iscritto": "IMU Dichiarazione ISCRITTO",
  "op_730_unico_imu__imu_dichiarazione_non_iscritto": "IMU Dichiarazione NON ISCRITTO",
  "op_730_unico_imu__mod_redditi_iscritto": "Mod. REDDITI ISCRITTO",
  "op_730_unico_imu__mod_redditi_non_iscritto": "Mod. REDDITI NON ISCRITTO",
  "op_730_unico_imu__mod_redditi_solo_trasmissione_telematica": "Mod. REDDITI solo trasmissione telematica",
  "op_patronato__allegare_documento_a_pratica_assegno_unico_universale": "ALLEGARE DOCUMENTO A PRATICA ASSEGNO UNICO UNIVERSALE",
  "op_patronato__altre_richieste_previdenziali_pensione_congedo_104_ricongiun": "ALTRE RICHIESTE PREVIDENZIALI (pensione, congedo 104, ricongiunzione, riversibilità, congedo matrimoniale)",
  "op_patronato__assegno_unico_universale": "ASSEGNO UNICO UNIVERSALE",
  "op_patronato__bonus_asilo_nido": "BONUS ASILO NIDO",
  "op_patronato__bonus_sociale_livello_1": "BONUS SOCIALE LIVELLO 1",
  "op_patronato__bonus_sociale_livello_2": "BONUS SOCIALE LIVELLO 2",
  "op_patronato__calcolo_della_pensione_stampa_estratto_conto_contributivo": "CALCOLO DELLA PENSIONE + STAMPA ESTRATTO CONTO CONTRIBUTIVO",
  "op_patronato__compilazione_modulistica_es_richiesta_aler": "COMPILAZIONE MODULISTICA (ES. RICHIESTA ALER…)",
  "op_patronato__comunicazioni_all_inps": "COMUNICAZIONI ALL'INPS",
  "op_patronato__correzione_assegno_unico_universale": "CORREZIONE ASSEGNO UNICO UNIVERSALE",
  "op_patronato__dimissioni_volontarie": "DIMISSIONI VOLONTARIE",
  "op_patronato__domanda_casa_populare": "DOMANDA CASA POPULARE",
  "op_patronato__dote_scuola": "DOTE SCUOLA",
  "op_patronato__duplicati_bolletini_inps": "DUPLICATI BOLLETINI INPS",
  "op_patronato__inserimento_neonato_in_assegno_unico_universale": "INSERIMENTO NEONATO IN ASSEGNO UNICO UNIVERSALE",
  "op_patronato__maternita": "MATERNITA'",
  "op_patronato__naspi": "NASPI",
  "op_patronato__reddito_di_cittadinanza": "REDDITO DI CITTADINANZA",
  "op_patronato__richiesta_e_stampa_estratto_conto_contributivo": "RICHIESTA E STAMPA ESTRATTO CONTO CONTRIBUTIVO",
  "op_patronato__richiesta_estrato_conto_contributivo_certificato": "RICHIESTA ESTRATO CONTO CONTRIBUTIVO CERTIFICATO",
  "op_patronato__richiesta_pensione_ricalcolo": "RICHIESTA PENSIONE / RICALCOLO",
  "op_patronato__ricostituzione_motivi_documentali_inps": "RICOSTITUZIONE MOTIVI DOCUMENTALI INPS",
  "op_patronato__stampa_modello_cu_inps_categoria_pensionati_naspi": "STAMPA MODELLO CU INPS (categoria pensionati / NASPI)",
  "op_patronato__stampa_modello_obis_m": "STAMPA MODELLO OBIS-M",
  "op_immigrazione__decreto_flussi": "DECRETO FLUSSI",
  "op_immigrazione__dichiarazione_garanzia_e_o_alloggio_per_richiesta_visto_turi": "DICHIARAZIONE GARANZIA E/O ALLOGGIO PER RICHIESTA VISTO TURISTICO",
  "op_immigrazione__fidejussione_per_turismo_altri_paesi_verificare_requisiti_pa": "FIDEJUSSIONE PER TURISMO ALTRI PAESI (verificare requisiti paese d'origine)",
  "op_immigrazione__fidejussione_per_turismo_ecuador_include_assicurazione_sanit": "FIDEJUSSIONE PER TURISMO ECUADOR (include assicurazione sanitaria)",
  "op_immigrazione__idonieta_alloggiativa": "IDONIETA' ALLOGGIATIVA",
  "op_immigrazione__modulo_di_ospitalita_per_cittadino_extracomunitario": "MODULO DI OSPITALITA' (per cittadino extracomunitario)",
  "op_immigrazione__richiesta_aggiornamento_permesso_di_soggiorno": "RICHIESTA AGGIORNAMENTO PERMESSO DI SOGGIORNO",
  "op_immigrazione__richiesta_appuntamento_codice_fiscale": "RICHIESTA APPUNTAMENTO CODICE FISCALE",
  "op_immigrazione__richiesta_appuntamento_giuramento_cittadinanza_italiana": "RICHIESTA APPUNTAMENTO GIURAMENTO CITTADINANZA ITALIANA",
  "op_immigrazione__richiesta_appuntamento_per_idoneita_alloggiativa": "RICHIESTA APPUNTAMENTO PER IDONEITA' ALLOGGIATIVA",
  "op_immigrazione__richiesta_appuntamento_per_test_lingua_italiana": "RICHIESTA APPUNTAMENTO PER TEST LINGUA ITALIANA",
  "op_immigrazione__richiesta_cittadinanza_italiana": "RICHIESTA CITTADINANZA ITALIANA",
  "op_immigrazione__richiesta_ricongiungimento_familiare": "RICHIESTA RICONGIUNGIMENTO FAMILIARE",
  "op_immigrazione__richiesta_rinnovo_permesso_di_soggiorno_per_studenti": "RICHIESTA RINNOVO PERMESSO DI SOGGIORNO PER STUDENTI",
  "op_immigrazione__rilascio_richiesta_rinnovo_permesso_di_soggiorno_carta_di_so": "RILASCIO/RICHIESTA RINNOVO PERMESSO DI SOGGIORNO/CARTA DI SOGGIORNO",
  "op_immigrazione__rilascio_richiesta_rinnovo_permesso_carta_di_soggiorno_con_f": "RILASCIO/RICHIESTA RINNOVO PERMESSO/CARTA DI SOGGIORNO CON FAMILIARE A CARICO",
  "op_immigrazione__rinnovo_altri_tipi_di_permesso_di_soggiorno": "RINNOVO ALTRI TIPI DI PERMESSO DI SOGGIORNO",
  "op_colf_e_badanti__apertura_contratto_consulenza_e_scelta_profilo_contrattuale_": "APERTURA CONTRATTO (Consulenza e scelta profilo contrattuale, redazione contratto, assunzione, gestione pratiche burocratiche)",
  "op_colf_e_badanti__calcolo_tfr_annuo_una_tantum_senza_gestione_ordinaria": "CALCOLO TFR ANNUO (una tantum, senza gestione ordinaria)",
  "op_colf_e_badanti__consulenza_contrattuale_informazioni_senza_apertura_contratt": "CONSULENZA CONTRATTUALE (Informazioni senza apertura contratto)",
  "op_colf_e_badanti__controllo_busta_paga_una_tantum_senza_gestione_ordinaria": "CONTROLLO BUSTA PAGA (una tantum, senza gestione ordinaria)",
  "op_colf_e_badanti__dimissione_colf": "DIMISSIONE COLF",
  "op_colf_e_badanti__elaborazione_controllo_cu": "ELABORAZIONE/CONTROLLO CU",
  "op_colf_e_badanti__gestione_busta_paga_annuale_elaborazione_e_registrazione_del": "GESTIONE BUSTA PAGA ANNUALE (elaborazione e registrazione del contratto, elaborazione busta paga, MAV, calcolo TFR, elaborazione CU)",
  "op_colf_e_badanti__gestione_ordinaria_contratto_annuale_stampa_buste_paga_bolle": "GESTIONE ORDINARIA CONTRATTO ANNUALE (Stampa buste paga, bollettini contributi Inps, CU, consulenza su variazioni contrattuali)",
  "op_colf_e_badanti__gestione_ordinaria_contratto_mensile_stampa_buste_paga_bolle": "GESTIONE ORDINARIA CONTRATTO MENSILE (Stampa buste paga, bollettini contributi Inps, CU, consulenza su variazioni contrattuali)",
  "op_colf_e_badanti__gestione_ordinaria_contratto_trimestrale_stampa_buste_paga_b": "GESTIONE ORDINARIA CONTRATTO TRIMESTRALE (Stampa buste paga, bollettini contributi Inps, CU, consulenza su variazioni contrattuali)",
  "op_colf_e_badanti__licenziamento_colf_badante_datore_di_lavoro": "LICENZIAMENTO COLF/BADANTE (datore di lavoro)",
  "op_colf_e_badanti__pratiche_cassa_colf": "PRATICHE CASSA COLF",
  "op_colf_e_badanti__variazione_contrattuale_chiusura_contratto_comunicazione_ed_": "VARIAZIONE CONTRATTUALE/CHIUSURA CONTRATTO\\n(Comunicazione ed adempimenti connessi)",
  "op_locazione__chiusura_contratto_di_locazione": "CHIUSURA CONTRATTO DI LOCAZIONE",
  "op_locazione__registrazione_contratto_locazione": "REGISTRAZIONE CONTRATTO LOCAZIONE",
  "op_locazione__stesura_e_invio_contratto_di_locazione_ad_uso_abitativo": "STESURA E INVIO CONTRATTO DI LOCAZIONE AD USO ABITATIVO",
  "op_locazione__subentro_del_contratto_di_locazione": "SUBENTRO DEL CONTRATTO DI LOCAZIONE",
  "op_sportello_famiglia__accompagnamento_famiglia_inserire_tariffa_a_seconda_di_chi_p": "ACCOMPAGNAMENTO FAMIGLIA (inserire tariffa a seconda di chi paga: famiglia o coop.sociale)",
  "op_sportello_famiglia__iscrizione_scuola_neo_arrivati_inserire_tariffa_a_seconda_di": "ISCRIZIONE SCUOLA NEO-ARRIVATI (inserire tariffa a seconda di chi paga: famiglia o coop.sociale)",
  "op_sportello_famiglia__mediazione_linguistica_culturale_ambito_sanitario_inserire_t": "MEDIAZIONE LINGUISTICA/CULTURALE AMBITO SANITARIO (inserire tariffa a seconda di chi paga: famiglia o coop.sociale)",
  "op_sportello_famiglia__permesso_di_soggiorno_per_accompagnante_inserire_tariffa_a_s": "PERMESSO DI SOGGIORNO PER ACCOMPAGNANTE (inserire tariffa a seconda di chi paga: famiglia o coop.sociale)",
  "op_sportello_famiglia__permesso_di_soggiorno_per_assistenza_minori_inserire_tariffa": "PERMESSO DI SOGGIORNO PER ASSISTENZA MINORI (inserire tariffa a seconda di chi paga: famiglia o coop.sociale)",
  "op_sportello_famiglia__permesso_di_soggiorno_per_cure_mediche_inserire_tariffa_a_se": "PERMESSO DI SOGGIORNO PER CURE MEDICHE (inserire tariffa a seconda di chi paga: famiglia o coop.sociale)",
  "op_sportello_famiglia__permesso_di_soggiorno_per_gravidanza_inserire_tariffa_a_seco": "PERMESSO DI SOGGIORNO PER GRAVIDANZA (inserire tariffa a seconda di chi paga: famiglia o coop.sociale)",
  "op_autonomi_imprese__apertura_p_iva_gestione_separata": "APERTURA P.IVA GESTIONE SEPARATA",
  "op_autonomi_imprese__attribuzione_p_iva": "ATTRIBUZIONE P.IVA",
  "op_autonomi_imprese__chiusura_impresa": "CHIUSURA IMPRESA",
  "op_autonomi_imprese__chiusura_p_iva": "CHIUSURA P-IVA",
  "op_autonomi_imprese__contabilita_e_dichiarazione_riders": "CONTABILITÀ E DICHIARAZIONE RIDERS",
  "op_autonomi_imprese__contabilita_partita_iva_forfettaria": "CONTABILITÀ PARTITA IVA FORFETTARIA",
  "op_autonomi_imprese__iscrizione_gestione_separata": "ISCRIZIONE GESTIONE SEPARATA",
  "op_autonomi_imprese__nuova_impresa_trasporti_ambulanti": "NUOVA IMPRESA TRASPORTI/AMBULANTI",
  "op_autonomi_imprese__nuova_impresa_altre_categorie": "NUOVA IMPRESA/ALTRE CATEGORIE",
  "op_autonomi_imprese__tenuta_contabilita_aziendale": "TENUTA CONTABILITA' AZIENDALE",
  "op_autonomi_imprese__variazione_partita_iva": "VARIAZIONE PARTITA IVA",
  "op_successioni__dichiarazioni_integrative_pratiche_caf_cisl_consulenza_compi": "DICHIARAZIONI INTEGRATIVE -Pratiche CAF CISL (Consulenza, compilazione e presentazione variazioni dichiarazione di successione)",
  "op_successioni__ispezione_ipotecaria": "ISPEZIONE IPOTECARIA",
  "op_successioni__pratica_di_successione_maggiorazioni_per_ogni_bene_immobile_": "PRATICA DI SUCCESSIONE – MAGGIORAZIONI (per ogni bene immobile e/o Istituto aggiuntivo)",
  "op_successioni__pratica_di_successione_solo_patrimonio_mobiliare": "PRATICA DI SUCCESSIONE – SOLO PATRIMONIO MOBILIARE",
  "op_successioni__pratica_di_successione_base_consulenza_compilazione_dichiara": "PRATICA DI SUCCESSIONE BASE (Consulenza, compilazione dichiarazione di successione e volture, trasmissione telematica dichiarazione A.E.)",
  "op_successioni__pratica_di_successione_max_consulenza_compilazione_dichiaraz": "PRATICA DI SUCCESSIONE MAX (Consulenza, compilazione dichiarazione di successione e volture, trasmissione telematica dichiarazione A.E.) SENZA LIMITI di BENI IMMOBILI e ISTITUTI",
  "op_successioni__riunione_di_usufrutto_e_volture_catastali_predisposizione_e_": "RIUNIONE DI USUFRUTTO E VOLTURE CATASTALI (Predisposizione e presentazione della documentazione)",
  "op_successioni__segnalazione_errore_al_catasto": "SEGNALAZIONE ERRORE AL CATASTO",
  "op_successioni__trasmissione_telematica_dichiarazione_precompilata": "TRASMISSIONE TELEMATICA DICHIARAZIONE PRECOMPILATA",
  "op_servizi_finanziari__cessione_del_quinto": "CESSIONE DEL QUINTO",
  "op_servizi_finanziari__consulenza_per_valutazione_rating_creditizio": "CONSULENZA PER VALUTAZIONE RATING CREDITIZIO",
  "op_servizi_finanziari__crif": "CRIF",
  "op_servizi_finanziari__microcredito_aziendale": "MICROCREDITO AZIENDALE",
  "op_servizi_finanziari__mutuo": "MUTUO",
  "op_servizi_finanziari__prestiti": "PRESTITI",
  "op_servizi_finanziari__saldi_a_stralcio": "SALDI A STRALCIO",
  "op_altri_servizi__assistenza_compilazione_f24_generico": "ASSISTENZA COMPILAZIONE F24 (Generico)",
  "op_altri_servizi__attivazione_spid": "ATTIVAZIONE SPID",
  "op_altri_servizi__autotutela_solo_compilazione_modello_precontenzioso_gestione": "AUTOTUTELA  - solo compilazione Modello (Precontenzioso: gestione comunicazioni-accertamenti Agenzia)",
  "op_altri_servizi__biglietteria": "BIGLIETTERIA",
  "op_altri_servizi__compilazione_moduli_vari": "COMPILAZIONE MODULI VARI",
  "op_altri_servizi__consulenza_generica": "CONSULENZA (Generica)",
  "op_altri_servizi__conteggi_imposte_anni_precedenti_pratiche_concaf_controllo_e": "CONTEGGI IMPOSTE ANNI PRECEDENTI - Pratiche CONCAF (Controllo e verifica conteggi Imu-Tasi-Irpef - max 5 anni)",
  "op_altri_servizi__conteggi_imposte_anni_precedenti_pratiche_non_concaf_control": "CONTEGGI IMPOSTE ANNI PRECEDENTI - Pratiche non CONCAF (Controllo e verifica conteggi Imu-Tasi-Irpef - max 5 anni)",
  "op_altri_servizi__firma_digitale": "FIRMA DIGITALE",
  "op_altri_servizi__invio_pec_varie_tipologie": "INVIO PEC (varie tipologie)",
  "op_altri_servizi__iscrizione_a_i_r_e_anagrafe_italiani_residenti_all_estero": "ISCRIZIONE A.I.R.E. (Anagrafe Italiani residenti all'estero)",
  "op_altri_servizi__iscrizione_bando_sport": "ISCRIZIONE BANDO SPORT",
  "op_altri_servizi__iscrizione_mensa_scolastica": "ISCRIZIONE MENSA SCOLASTICA",
  "op_altri_servizi__istanza_di_rimborso_solo_compilazione_modello_istanza_di_sgr": "ISTANZA DI RIMBORSO - solo compilazione Modello (Istanza di sgravio o di rimborso Imu-Tasi o Irpef)",
  "op_altri_servizi__modello_eas_e_iscrizione_5_per_mille_trasmissione": "MODELLO EAS e ISCRIZIONE 5 per mille(Trasmissione)",
  "op_altri_servizi__modello_red_isee_invciv_non_iscritti": "Modello RED – ISEE –INVCIV NON ISCRITTI",
  "op_altri_servizi__ravvedimento_precontenzioso_calcolo_elaborazione_e_stampa_f2": "RAVVEDIMENTO (Precontenzioso: calcolo-elaborazione e stampa F24 ravvedimento operoso 730-Unico-Imu)",
  "op_altri_servizi__richiesta_appuntamento_per_passaporto": "RICHIESTA APPUNTAMENTO PER PASSAPORTO",
  "op_altri_servizi__richiesta_stato_di_famiglia": "RICHIESTA STATO DI FAMIGLIA",
  "op_altri_servizi__ristampa_di_un_qualsiasi_modello_gia_compilato_elaborato_in_": "RISTAMPA (di un qualsiasi modello già compilato elaborato in CONCAF)",
  "op_altri_servizi__sblocco_spid_altri_gestori": "SBLOCCO SPID ALTRI GESTORI",
  "op_altri_servizi__sblocco_spid_namirial": "SBLOCCO SPID NAMIRIAL",
  "op_altri_servizi__stampa_modello_c_u_senza_fruizione_di_servizi_caf": "STAMPA MODELLO C.U. (senza fruizione di servizi CAF)",
  "op_altri_servizi__tessera_atm": "TESSERA ATM",
  "op_altri_servizi__tessera_concaf": "TESSERA CONCAF",
  "op_altri_servizi__traduzione_giurata": "TRADUZIONE GIURATA",
  "op_altri_servizi__trasmissione_telematica_f24": "TRASMISSIONE TELEMATICA F24",
  "op_altri_servizi__visure_camerale_consultazione_e_stampa": "VISURE CAMERALE (consultazione e stampa)",
  "op_altri_servizi__visure_catastali_consultazione_e_stampa": "VISURE CATASTALI (consultazione e stampa)",
};

const Map<String, String> kOperativoCategoryLabels = {
  "730_unico_imu": "730–UNICO–IMU",
  "patronato": "PATRONATO",
  "immigrazione": "IMMIGRAZIONE",
  "colf_e_badanti": "COLF E BADANTI",
  "locazione": "LOCAZIONE",
  "sportello_famiglia": "SPORTELLO FAMIGLIA",
  "autonomi_imprese": "AUTONOMI/IMPRESE",
  "successioni": "SUCCESSIONI",
  "servizi_finanziari": "SERVIZI FINANZIARI",
  "altri_servizi": "ALTRI SERVIZI",
};

